dynamo: Don't crash when tracing a missing attr on a constant or enum.
This throws a InternalTorchDynamoError: AttributeError: 'NoneType' object has no attribute 'max'
instead of just skipping the bad call when tracing, and throwing a
normal AttributeError instead.

There are two questions that I would love reviewer comment on.
1) Is throwing unimplemented the right thing here? or should I throw
   something like ObservedAttributeError
2) Do we need to worry about performance with this code? In particular,
   should we just catch the exception? Or maybe cache the lookup result?

ghstack-source-id: 5bc72d1f8447801a97bb39a1c953ceae6dc6d792
Pull Request resolved: https://github.com/pytorch/pytorch/pull/144593